language: java

jdk:
  - oraclejdk8

sudo: false
notifications:
  slack:
    rooms:
      - babysmith:ULSqFgVgfIwVZhqtqM7d27kv#git
      - babysmith:ULSqFgVgfIwVZhqtqM7d27kv#hyperlib
addons:
  apt:
    packages:
      - oracle-java8-installer
